apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: mlops-docs
type: docker-registry
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsiYXV0aCI6IkhXYWRtaW46bWluaWFkbWluMTIzIn19fQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: mlops-config
  namespace: mlops-docs
type: Opaque
stringData:
  config: |
    {
      "environment": "production",
      "logLevel": "info"
    }
