apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-docs
  namespace: mlops-docs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlops-docs
  namespace: mlops-docs
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlops-docs
  namespace: mlops-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mlops-docs
subjects:
  - kind: ServiceAccount
    name: mlops-docs
    namespace: mlops-docs
